# Task 1: 

Question 1:

        Write a function to compute 5/0 and use try/except to catch the exceptions

In [2]:
try:
    val=int(input("Enter an integer   \t "))
    res=5/val
    print(" The result is",res)
except Exception as e:
    print(e)
    

Enter an integer   	 0
division by zero


# Question 2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 


Output should come as below: 
 
Americans  play Baseball.

Americans  play Cricket.

Americans  watch Baseball.

Americans  watch Cricket. 

Indians play Baseball. 

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket. 


In [3]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

In [37]:
combinations=[(s+" " + v+ " "+ o) for s in subjects for v in verbs for o in objects]

In [38]:
print(combinations)

['Americans  play Baseball', 'Americans  play Cricket', 'Americans  watch Baseball', 'Americans  watch Cricket', 'Indians play Baseball', 'Indians play Cricket', 'Indians watch Baseball', 'Indians watch Cricket']


In [39]:
for i in combinations:
    print(i)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:  
 
 
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 
 
 

Parameters:	
x : array_like

1-D input array.

N : int, optional

Order of (number of columns in) the output. If N is not specified, a square array is returned (N = len(x)).

Returns:	
out : ndarray

Van der Monde matrix of order N. The first column is x^(N-1), the second x^(N-2) and so forth.



# Solution to the question

In [48]:
## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 

In [50]:
import numpy as np

In [70]:
vect=np.array([1,2,3,4])
print("Size of array",vect.size)

col=3
def vander_matrix(arr,n,increasing=False):
    if not increasing:
        res_matrix=np.column_stack([x**(n-i-1) for x in arr for i in range(n)]).reshape(arr.size,n)
    else:
         res_matrix=np.column_stack([x**i for x in arr for i in range(n)]).reshape(arr.size,n)
                
    return res_matrix
print("-"*10)
print("Input array is  :",vect,"\n")
print("Number of columns  :",col,"\n")

res_matrix_dec=vander_matrix(vect,col,False)
res_matrix_inc=vander_matrix(vect,col,True)
print("Vander matrix in decreasing order of power\n\n",res_matrix_dec)

print("Vander matrix in increasing order of power \n\n",res_matrix_inc)
        
    


Size of array 4
----------
Input array is  : [1 2 3 4] 

Number of columns  : 3 

Vander matrix in decreasing order of power

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
Vander matrix in increasing order of power 

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
